# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manual.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlg_manual(object):
    def setupUi(self, dlg_manual):
        dlg_manual.setObjectName("dlg_manual")
        dlg_manual.resize(671, 376)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/mian_background/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dlg_manual.setWindowIcon(icon)
        dlg_manual.setStyleSheet("#dlg_manual{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.227, y1:0.46, x2:0.886, y2:0.193182, stop:0 rgba(191, 189, 255, 255), stop:0.596591 rgba(131, 202, 235, 255), stop:1 rgba(159, 214, 208, 255));\n"
"}\n"
"QPushButton{\n"
"    height: 22px;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(85, 170, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    font:15px \"SimSun\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 85, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(0, 0, 255);\n"
"}\n"
"\n"
"\n"
"\n"
"QSlider::groove:horizontal{ \n"
"    height: 12px; \n"
"    left: 0px; \n"
"    right: 0px; \n"
"    border:0px; \n"
"    border-radius:6px;   \n"
"    background:rgba(0,0,0,50);\n"
" } \n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: rgb(161, 199, 255);\n"
"\n"
"}\n"
"\n"
" QSlider::handle:horizontal{ \n"
"    width:  12px; \n"
"    border-radius:6px;  \n"
"    \n"
"    background-color: rgb(0, 170, 255);\n"
"        \n"
"} \n"
"\n"
"\n"
"")
        self.gridLayout_4 = QtWidgets.QGridLayout(dlg_manual)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(dlg_manual)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pushButton_gripper_m = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_gripper_m.setObjectName("pushButton_gripper_m")
        self.gridLayout_7.addWidget(self.pushButton_gripper_m, 0, 0, 1, 1)
        self.pushButton_gripper_p = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_gripper_p.setObjectName("pushButton_gripper_p")
        self.gridLayout_7.addWidget(self.pushButton_gripper_p, 0, 1, 1, 1)
        self.pushButton_sucker = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_sucker.setCheckable(True)
        self.pushButton_sucker.setObjectName("pushButton_sucker")
        self.gridLayout_7.addWidget(self.pushButton_sucker, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(dlg_manual)
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox1 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox1.sizePolicy().hasHeightForWidth())
        self.groupBox1.setSizePolicy(sizePolicy)
        self.groupBox1.setStyleSheet("QGroupBox{\n"
"border: opx solid;\n"
"}\n"
"QPushButton{\n"
"    height: 30px;\n"
"}")
        self.groupBox1.setObjectName("groupBox1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox1)
        self.gridLayout_2.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_zm = QtWidgets.QPushButton(self.groupBox1)
        self.pushButton_zm.setObjectName("pushButton_zm")
        self.gridLayout_2.addWidget(self.pushButton_zm, 0, 0, 1, 1)
        self.pushButton_rm = QtWidgets.QPushButton(self.groupBox1)
        self.pushButton_rm.setObjectName("pushButton_rm")
        self.gridLayout_2.addWidget(self.pushButton_rm, 0, 1, 1, 1)
        self.pushButton_rp = QtWidgets.QPushButton(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_rp.sizePolicy().hasHeightForWidth())
        self.pushButton_rp.setSizePolicy(sizePolicy)
        self.pushButton_rp.setObjectName("pushButton_rp")
        self.gridLayout_2.addWidget(self.pushButton_rp, 1, 1, 1, 1)
        self.pushButton_zp = QtWidgets.QPushButton(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_zp.sizePolicy().hasHeightForWidth())
        self.pushButton_zp.setSizePolicy(sizePolicy)
        self.pushButton_zp.setObjectName("pushButton_zp")
        self.gridLayout_2.addWidget(self.pushButton_zp, 1, 0, 1, 1)
        self.pushButton_home = QtWidgets.QPushButton(self.groupBox1)
        self.pushButton_home.setObjectName("pushButton_home")
        self.gridLayout_2.addWidget(self.pushButton_home, 2, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox1, 0, 2, 1, 1)
        self.groupBox2 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox2.sizePolicy().hasHeightForWidth())
        self.groupBox2.setSizePolicy(sizePolicy)
        self.groupBox2.setStyleSheet("QGroupBox{\n"
"border: opx solid;\n"
"}")
        self.groupBox2.setObjectName("groupBox2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Slider_accel = QtWidgets.QSlider(self.groupBox2)
        self.Slider_accel.setMinimum(1)
        self.Slider_accel.setMaximum(300)
        self.Slider_accel.setProperty("value", 30)
        self.Slider_accel.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_accel.setObjectName("Slider_accel")
        self.gridLayout_3.addWidget(self.Slider_accel, 2, 2, 1, 1)
        self.label_dis = QtWidgets.QLabel(self.groupBox2)
        self.label_dis.setObjectName("label_dis")
        self.gridLayout_3.addWidget(self.label_dis, 0, 0, 1, 2)
        self.Slider_curve = QtWidgets.QSlider(self.groupBox2)
        self.Slider_curve.setMaximum(8)
        self.Slider_curve.setProperty("value", 0)
        self.Slider_curve.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_curve.setObjectName("Slider_curve")
        self.gridLayout_3.addWidget(self.Slider_curve, 3, 2, 1, 1)
        self.label_accel = QtWidgets.QLabel(self.groupBox2)
        self.label_accel.setObjectName("label_accel")
        self.gridLayout_3.addWidget(self.label_accel, 2, 0, 1, 2)
        self.Slider_speed = QtWidgets.QSlider(self.groupBox2)
        self.Slider_speed.setMinimum(1)
        self.Slider_speed.setMaximum(300)
        self.Slider_speed.setProperty("value", 100)
        self.Slider_speed.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_speed.setObjectName("Slider_speed")
        self.gridLayout_3.addWidget(self.Slider_speed, 1, 1, 1, 2)
        self.label_curve = QtWidgets.QLabel(self.groupBox2)
        self.label_curve.setObjectName("label_curve")
        self.gridLayout_3.addWidget(self.label_curve, 3, 0, 1, 2)
        self.label_speed = QtWidgets.QLabel(self.groupBox2)
        self.label_speed.setObjectName("label_speed")
        self.gridLayout_3.addWidget(self.label_speed, 1, 0, 1, 1)
        self.Slider_dis = QtWidgets.QSlider(self.groupBox2)
        self.Slider_dis.setMinimum(1)
        self.Slider_dis.setMaximum(300)
        self.Slider_dis.setProperty("value", 20)
        self.Slider_dis.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_dis.setObjectName("Slider_dis")
        self.gridLayout_3.addWidget(self.Slider_dis, 0, 2, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox2, 1, 2, 1, 1)
        self.groupBox3 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox3.sizePolicy().hasHeightForWidth())
        self.groupBox3.setSizePolicy(sizePolicy)
        self.groupBox3.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox3.setMaximumSize(QtCore.QSize(500, 16777215))
        self.groupBox3.setStyleSheet("QGroupBox{\n"
"border: opx solid;\n"
"}\n"
"QPushButton{\n"
"    height: 40px;\n"
"}")
        self.groupBox3.setObjectName("groupBox3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox3)
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_xp = QtWidgets.QPushButton(self.groupBox3)
        self.pushButton_xp.setObjectName("pushButton_xp")
        self.gridLayout.addWidget(self.pushButton_xp, 1, 3, 1, 1)
        self.pushButton_xm = QtWidgets.QPushButton(self.groupBox3)
        self.pushButton_xm.setObjectName("pushButton_xm")
        self.gridLayout.addWidget(self.pushButton_xm, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.pushButton_yp = QtWidgets.QPushButton(self.groupBox3)
        self.pushButton_yp.setObjectName("pushButton_yp")
        self.gridLayout.addWidget(self.pushButton_yp, 0, 2, 1, 1)
        self.pushButton_ym = QtWidgets.QPushButton(self.groupBox3)
        self.pushButton_ym.setObjectName("pushButton_ym")
        self.gridLayout.addWidget(self.pushButton_ym, 2, 2, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox3, 0, 0, 2, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 2)
        self.groupBox_3 = QtWidgets.QGroupBox(dlg_manual)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton_belt_stop = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_belt_stop.setObjectName("pushButton_belt_stop")
        self.gridLayout_6.addWidget(self.pushButton_belt_stop, 0, 5, 1, 1)
        self.label_belt_speed = QtWidgets.QLabel(self.groupBox_3)
        self.label_belt_speed.setObjectName("label_belt_speed")
        self.gridLayout_6.addWidget(self.label_belt_speed, 1, 0, 1, 1)
        self.Slider_belt_speed = QtWidgets.QSlider(self.groupBox_3)
        self.Slider_belt_speed.setProperty("value", 0)
        self.Slider_belt_speed.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_belt_speed.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.Slider_belt_speed.setObjectName("Slider_belt_speed")
        self.gridLayout_6.addWidget(self.Slider_belt_speed, 1, 1, 1, 5)
        self.pushButton_belt_m = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_belt_m.setObjectName("pushButton_belt_m")
        self.gridLayout_6.addWidget(self.pushButton_belt_m, 0, 4, 1, 1)
        self.pushButton_belt_p = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_belt_p.setObjectName("pushButton_belt_p")
        self.gridLayout_6.addWidget(self.pushButton_belt_p, 0, 3, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 1, 1, 1, 1)

        self.retranslateUi(dlg_manual)
        QtCore.QMetaObject.connectSlotsByName(dlg_manual)

    def retranslateUi(self, dlg_manual):
        _translate = QtCore.QCoreApplication.translate
        dlg_manual.setWindowTitle(_translate("dlg_manual", "Manual"))
        self.groupBox_2.setTitle(_translate("dlg_manual", "夹爪"))
        self.pushButton_gripper_m.setText(_translate("dlg_manual", "闭合"))
        self.pushButton_gripper_p.setText(_translate("dlg_manual", "打开"))
        self.pushButton_sucker.setText(_translate("dlg_manual", "吸盘"))
        self.groupBox.setTitle(_translate("dlg_manual", "机器人"))
        self.pushButton_zm.setText(_translate("dlg_manual", "Z-"))
        self.pushButton_rm.setText(_translate("dlg_manual", "R-"))
        self.pushButton_rp.setText(_translate("dlg_manual", "R+"))
        self.pushButton_zp.setText(_translate("dlg_manual", "Z+"))
        self.pushButton_home.setText(_translate("dlg_manual", "home"))
        self.label_dis.setText(_translate("dlg_manual", "位移量(mm)"))
        self.label_accel.setText(_translate("dlg_manual", "加速度(%)"))
        self.label_curve.setText(_translate("dlg_manual", "曲线"))
        self.label_speed.setText(_translate("dlg_manual", "速度(%)"))
        self.pushButton_xp.setText(_translate("dlg_manual", "X+"))
        self.pushButton_xm.setText(_translate("dlg_manual", "X-"))
        self.pushButton_yp.setText(_translate("dlg_manual", "Y+"))
        self.pushButton_ym.setText(_translate("dlg_manual", "Y-"))
        self.groupBox_3.setTitle(_translate("dlg_manual", "传送带"))
        self.pushButton_belt_stop.setText(_translate("dlg_manual", "传送带停止"))
        self.label_belt_speed.setText(_translate("dlg_manual", "速度"))
        self.pushButton_belt_m.setText(_translate("dlg_manual", "传送带反转"))
        self.pushButton_belt_p.setText(_translate("dlg_manual", "传送带正转"))
import main_rc
